#version: "3.9"
#
#services:
#  # 1. Container Cơ sở dữ liệu (MSSQL)
#  sql_server:
#    image: mcr.microsoft.com/mssql/server:2022-latest # mssql/server:2022-latest
#    container_name: SQL
#    ports:
#      - "1433:1433"
#    environment:
#      - ACCEPT_EULA=Y
#      - MSSQL_SA_PASSWORD=Abc@123456 # Hãy đổi thành mật khẩu thực tế của bạn
#    volumes:
#      - mssql_data:/var/opt/mssql
#
#  # 2. Container Backend (Spring Boot)
#  backend:
#    build: .
#    container_name: cosmate-backend
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#
#      # Co j xoa ca nay
#    environment:
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sql_server:1433;databaseName=CosMate;encrypt=true;trustServerCertificate=true;
#    depends_on:
#      - sql_server # Giúp Docker biết phải bật Database lên trước rồi mới bật Backend
#
#  npm:
#    image: 'jc21/nginx-proxy-manager:latest'
#    container_name: nginx-proxy-manager
#    restart: unless-stopped
#    ports:
#      - '80:80'
#      - '81:81'
#      - '443:443'
#    volumes:
#      - ./data:/data
#      - ./letsencrypt:/etc/letsencrypt
#
#volumes:
#  mssql_data: # Khai báo volume tên là mssql_data

services:
  # 1. Cơ sở dữ liệu (MSSQL)
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SQL
    restart: always
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Abc@123456
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - cosmate_network

  # 2. Backend (Spring Boot)
  backend:
    build: .
    container_name: cosmate-backend
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sql_server:1433;databaseName=CosMate;encrypt=true;trustServerCertificate=true;
    depends_on:
      - sql_server
    networks:
      - cosmate_network

  # 4. Nginx Proxy Manager (Quản lý Domain & SSL)
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'   # Cổng web mặc định
      - '81:81'   # Giao diện quản trị NPM
      - '443:443' # Cổng HTTPS bảo mật
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - cosmate_network

networks:
  cosmate_network:
    driver: bridge

volumes:
  mssql_data: