package com.cosmate.dto.request;
import lombok.Data;

@Data
public class RecommendationRequest {
    private String gender;      // Nam/Nữ
    private String style;       // Cute, Cool, Sexy, Cổ trang...
    private String favoriteColor; // Đen, Hồng, Đỏ...
    private String budgetRange; // Thấp, Cao...
    private String hobby;       // Thích kiếm hiệp, thích bắn súng...
}